// <auto-generated />
using System;
using Exemplo.Web.Data.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exemplo.Web.Data.SqlServer.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20230607224941_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_cliente");

            modelBuilder.HasSequence<int>("seq_pedido");

            modelBuilder.HasSequence<int>("seq_produto");

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Cliente.ClienteEntidade", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR seq_cliente");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCliente");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Pedido.PedidoEntidade", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR seq_pedido");

                    b.Property<DateTime?>("DataHoraConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Pedido.PedidoItemEntidade", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("ValorUnit")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("IdPedido", "IdItem");

                    b.HasIndex("IdProduto");

                    b.ToTable("pedido_item", (string)null);
                });

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Produto.ProdutoEntidade", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR seq_produto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("IdProduto");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Pedido.PedidoEntidade", b =>
                {
                    b.HasOne("Exemplo.Web.Dominio.Entidades.Cliente.ClienteEntidade", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Pedido.PedidoItemEntidade", b =>
                {
                    b.HasOne("Exemplo.Web.Dominio.Entidades.Pedido.PedidoEntidade", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exemplo.Web.Dominio.Entidades.Produto.ProdutoEntidade", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Exemplo.Web.Dominio.Entidades.Pedido.PedidoEntidade", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
